### ISSUE TITLE
Weather Forecast only showing "Condition goes here"

### ISSUE THREAD

**Issue by AllesMeins** [pacjo/SmartspacerPlugins#11]
I've problems getting the "Weather Forecast" plugin to work. I've successfully connected it to Breezy Weather (The complication and the "generic weather plugin" work and show the current weather), but the forecast plugin only shows a black exklamation mark and the words "Condition goes here". Am I doing something wrong? I'm using the latest GitHub version of _Smartspacer_ and _SmartspacerPlugins_ and _Breezy Weather 5.2.3_freenet_.

**Comment by pacjo** [comment]
Can you share a screenshot of the issue and the smart spacer configuration?

**Comment by AllesMeins** [comment]
Yes of cause - is this what you need?

![Screenshot_20240620-123047](https://github.com/pacjo/SmartspacerPlugins/assets/2261844/71db4aa9-42f8-470b-a64a-cdc76c584323)
![Screenshot_20240620-123110](https://github.com/pacjo/SmartspacerPlugins/assets/2261844/c9aec074-e1c9-4b86-a9e4-e5346c315ac9)
![Screenshot_20240620-123142](https://github.com/pacjo/SmartspacerPlugins/assets/2261844/23816682-9d25-4ea5-a494-856c52a816a2)
![Screenshot_20240620-123722](https://github.com/pacjo/SmartspacerPlugins/assets/2261844/4557fc37-1c7e-47b7-a0b0-caff201c1ed3)

**Comment by pacjo** [comment]
Ah, didn't know I pushed it sorry. Weather forecast isn't ready yet.

**Comment by pacjo** [comment]
Ok, I pushed the updated apks with the target disabled (among other things). They're available through plugin manager in the smartspacer app.

Can you test them? You should get prompted to remove the target (I'll add it back in the future).

**Comment by AllesMeins** [comment]
Thank you, so far I didn't get any update notification. And the plug-in manager still shows version 1.3.

**Comment by pacjo** [comment]
You won't. I didn't change the version number, since I still want to change a few thing. Just uninstall and reinstall from manager and you should be good to go.

**Comment by AllesMeins** [comment]
Ah, alright - yeah that worked. Than I'll just wait until the forecast plug-in is ready. Thanks

**Comment by pacjo** [comment]
Hey @AllesMeins , I think I got basic version of this target working. I'll be testing it over the coming days, can you try it out too?

[app-genericweather-release.zip](https://github.com/user-attachments/files/16460226/app-genericweather-release.zip)

**Comment by AllesMeins** [comment]
Of course, I've installed it just now and let you know what my experiences are in a few days.

**Comment by AllesMeins** [comment]
Just had some time to take a closer look. It seems like nothing much has changed - is it the correct file you linked? If I remember correctly when I opened this issue "Forecast" was a separate plug-in. Now I still only see the "generic weather" I've already been using the last weeks.

**Comment by pacjo** [comment]
It's the same plugin, byt there are multiple targets. One that shows forecast for the next couple of hours (using a carousel) and this one, which will show overall forecast for the day (between 9-11 in the morning) and also warnings if there's expected participation in the next 2 hours.

Naming isn't the best and will probably need to be changed. This new target has a cloud with rain and sun icon.

**Comment by AllesMeins** [comment]
I've been trying it for a few days now and I've to say I really like it! Especially the forecast for the next day "2° colder than today". I didn't have a chance to see the precipitation-warning since we had a stretch of nice weather for a change. 

I was just wondering: Might it be smarter to put each functionality ("Weather for today", "Weather for tomorrow", "Rain warning") in it's own target? That way a user could use SmartSpacers already build in "Requirements" to configure it completely to their liking at what times each functionality shows up (Myself for example would need weather for the day earlier, so I see it before I leave for work).

**Comment by pacjo** [comment]
In the email I saw something about forecast for tomorrow. From the edit  I guess you saw, that it's not mine, but I can add that.

I don't use a pixel rom, so it doesn't show up for me. Around what time does it show up and for how long?

> each functionality ("Weather for today", "Weather for tomorrow", "Rain warning") in it's own target?

I kind of want to avoid that, cause it means a lot of updates and makes a bit of a mess out of the configuration. Would toggles in settings suffice?

> at what times each functionality shows up (Myself for example would need weather for the day earlier, so I see it before I leave for work)

Yeah. For now I was mimicking google's at a glance, but time should be configurable. I'm still debating on how to do that, since I can't add "default" requirements and it would either be something that each user would need to set up, or I'll need to basically clone *Requirements'* functionality inside configuration. None of which I'm happy about.

**Comment by pacjo** [comment]
![Screenshot_20240812-220742_Lawnchair (Debug)~2](https://github.com/user-attachments/assets/d65ac66f-405f-4ec0-8dc4-9a6e77054b4e)

I might've messed up brackets somewhere, will fix.

Didn't do a lot of work on this recently, so this might be a reason to start again.

**Comment by AllesMeins** [comment]
> In the email I saw something about forecast for tomorrow. From the edit I guess you saw, that it's not mine, but I can add that.
> 
> I don't use a pixel rom, so it doesn't show up for me. Around what time does it show up and for how long?

It shows up at around 7pm for maybe 3 hours? I always forgot to check regularly. But I managed to create some screenshots of what the Pixel-Version is showing. There seem to be two different ways it shows the forecast for the next day (temperature differnce to today or a quick description of the rain-situation). I couldn't quite figure out why either one is displayed. Sometimes they are both displayed at the same day.

![Screenshot_20240816-092439](https://github.com/user-attachments/assets/c5d77fb0-c247-4422-9ff2-527bc1cdbdcb)
![Screenshot_20240816-101048](https://github.com/user-attachments/assets/b851a948-a7ed-4763-a921-70475d3b95af)
![Screenshot_20240816-210649](https://github.com/user-attachments/assets/1a5a2949-c83b-4395-a278-631956c35361)
![Screenshot_20240816-213221](https://github.com/user-attachments/assets/0728cb37-3fd8-4698-8a8a-186d7c006067)
![Screenshot_20240817-164837](https://github.com/user-attachments/assets/acf569e7-9727-42a8-a6f9-343fec2d0071)

> > each functionality ("Weather for today", "Weather for tomorrow", "Rain warning") in it's own target?
> 
> I kind of want to avoid that, cause it means a lot of updates and makes a bit of a mess out of the configuration. Would toggles in settings suffice?

> > at what times each functionality shows up (Myself for example would need weather for the day earlier, so I see it before I leave for work)
> 
> Yeah. For now I was mimicking google's at a glance, but time should be configurable. I'm still debating on how to do that, since I can't add "default" requirements and it would either be something that each user would need to set up, or I'll need to basically clone _Requirements'_ functionality inside configuration. None of which I'm happy about.

I don't have enough inside into the developing process to decide which way is better. Creating different targets would save you the hustle to build your own timeing-settings and it would be more flexible for the user. But I agree that it might make pushing and developing updates more complicated unless there is some shared code/shared libraries you can build for the core functions, so you'd have to update them only once.

> Another alternative would be [Sleep API](https://developers.google.com/location-context/sleep), with which it could show the target when user wakes up or goes to sleep, but it's a GMS dependency and I want to avoid that.

Me personally, I'm not very happy with the sleep functions of my Pixel. I only own it for a few month and I already stumbled multiple times over limitations where I couldn't properly depict my real sleeping times because google made some assumptions I couldn't overwrite. So I wouldn't be to sad if you chose to ignore Sleep API :-)

> I might've messed up brackets somewhere, will fix.

Either that, or the end of the world is coming. Although I'm a bit confused if "-271° hotter" means a fiery death or a new ice age is coming. But in either case you probably would have more important things to do, than finishing the plugin 😂
